module Mistral
  # Thin wrapper around Mistral's chat completions and embeddings endpoints.
  # There's no official Ruby SDK, but the API is plain JSON over HTTP, so a
  # hand-rolled client is a few lines, not a real gap.
  class Client
    BASE_URL = "https://api.mistral.ai/v1"

    class Error < StandardError; end

    def initialize(api_key: ENV.fetch("MISTRAL_API_KEY"))
      @api_key = api_key
      @connection = Faraday.new(url: BASE_URL) do |f|
        # exceptions: here is a superset of Faraday's own default (which is
        # just timeouts) — Faraday::RetriableResponse has to stay in the
        # list for retry_statuses to still trigger a retry at all, since
        # naming exceptions: explicitly replaces the default rather than
        # adding to it. Connection-level failures (a plain ECONNRESET, no
        # HTTP response at all) added on top of that, confirmed live
        # elsewhere in this app to not be retried otherwise.
        f.request :retry, max: 4, interval: 1, backoff_factor: 2,
                          retry_statuses: [ 429, 500, 502, 503 ],
                          exceptions: [
                            Faraday::RetriableResponse,
                            Faraday::ConnectionFailed,
                            Faraday::TimeoutError,
                            Errno::ECONNRESET,
                            Errno::ETIMEDOUT
                          ]
        f.adapter Faraday.default_adapter
      end
    end

    def chat(messages:, model: "mistral-small-latest", tools: nil, tool_choice: nil)
      body = { model: model, messages: messages }
      body[:tools] = tools if tools.present?
      body[:tool_choice] = tool_choice if tool_choice.present?

      post("chat/completions", body)
    end

    # inputs: a string or array of strings. Returns an array of float arrays,
    # one embedding per input, in the same order.
    def embed(inputs, model: "mistral-embed")
      response = post("embeddings", { model: model, input: Array(inputs) })
      response["data"].sort_by { |d| d["index"] }.map { |d| d["embedding"] }
    end

    # Returns the parsed response — an array of pages, each with a
    # "markdown" field giving that page's text in clean reading order
    # (handles multi-column layouts correctly, unlike naive PDF text
    # extraction). Charts/figures are replaced with a bare image reference
    # in the markdown by default — pass bbox_annotation_format (or leave
    # the default on) to also get a real description of what each one
    # shows, generated by a vision model as part of this same call.
    def ocr(document_url:, model: "mistral-ocr-latest", bbox_annotation_format: DEFAULT_BBOX_ANNOTATION_FORMAT)
      body = { model: model, document: { type: "document_url", document_url: document_url } }
      body[:bbox_annotation_format] = bbox_annotation_format if bbox_annotation_format
      post("ocr", body)
    end

    DEFAULT_BBOX_ANNOTATION_FORMAT = {
      type: "json_schema",
      json_schema: {
        name: "figure_description",
        schema: {
          type: "object",
          properties: {
            description: {
              type: "string",
              description: "Describe this chart, graph, or figure in detail in Swedish, " \
                            "including every data value, label, and number it shows."
            }
          },
          required: [ "description" ]
        }
      }
    }.freeze

    private

    def post(path, body)
      response = @connection.post(path) do |req|
        req.headers["Content-Type"] = "application/json"
        req.headers["Authorization"] = "Bearer #{@api_key}"
        req.body = body.to_json
      end

      unless response.success?
        raise Error, "Mistral API error #{response.status}: #{response.body}"
      end

      JSON.parse(response.body.force_encoding(Encoding::UTF_8))
    end
  end
end
