# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production: &data_coverage
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  import_missing_votes:
    class: "Riksdagen::ImportMissingVotesJob"
    schedule: every 10 minutes
  enrich_documents:
    class: "Riksdagen::EnrichDocumentsJob"
    schedule: every 2 minutes

development:
  <<: *data_coverage
